
import { Componente, ComponentCategory } from '../types';

export const MOCK_COMPONENTS: Componente[] = [
  // CPUs
  {
    id: 'cpu1',
    tipo: ComponentCategory.CPU, // Changed from category to tipo
    nome: 'AMD Ryzen 5 5600X', // Changed from name to nome
    brand: 'AMD',
    preco: 1200, // Changed from price to preco
    imageUrl: 'https://picsum.photos/seed/cpu1/200/200',
    especificacao: { socket: 'AM4', cores: 6, threads: 12, base_clock: '3.7GHz', boost_clock: '4.6GHz', tdp: 65 }, // Changed from specs to especificacao
    compatibilityKey: 'AM4',
  },
  {
    id: 'cpu2',
    tipo: ComponentCategory.CPU,
    nome: 'Intel Core i5-12400F',
    brand: 'Intel',
    preco: 1000,
    imageUrl: 'https://picsum.photos/seed/cpu2/200/200',
    especificacao: { socket: 'LGA1700', cores: 6, threads: 12, base_clock: '2.5GHz', boost_clock: '4.4GHz', tdp: 65 },
    compatibilityKey: 'LGA1700',
  },
  {
    id: 'cpu3',
    tipo: ComponentCategory.CPU,
    nome: 'AMD Ryzen 7 7700X',
    brand: 'AMD',
    preco: 2200,
    imageUrl: 'https://picsum.photos/seed/cpu3/200/200',
    especificacao: { socket: 'AM5', cores: 8, threads: 16, base_clock: '4.5GHz', boost_clock: '5.4GHz', tdp: 105 },
    compatibilityKey: 'AM5',
  },
  {
    id: 'cpu4',
    tipo: ComponentCategory.CPU,
    nome: 'Intel Core i7-13700K',
    brand: 'Intel',
    preco: 2800,
    imageUrl: 'https://picsum.photos/seed/cpu4/200/200',
    especificacao: { socket: 'LGA1700', cores: 16, threads: 24, base_clock: '3.4GHz', boost_clock: '5.4GHz', tdp: 125 },
    compatibilityKey: 'LGA1700',
  },
  {
    id: 'cpu5',
    tipo: ComponentCategory.CPU,
    nome: 'AMD Ryzen 9 7900X',
    brand: 'AMD',
    preco: 3200,
    imageUrl: 'https://picsum.photos/seed/cpu5/200/200',
    especificacao: { socket: 'AM5', cores: 12, threads: 24, base_clock: '4.7GHz', boost_clock: '5.6GHz', tdp: 170 },
    compatibilityKey: 'AM5',
  },
  {
    id: 'cpu6',
    tipo: ComponentCategory.CPU,
    nome: 'Intel Core i3-12100F',
    brand: 'Intel',
    preco: 600,
    imageUrl: 'https://picsum.photos/seed/cpu6/200/200',
    especificacao: { socket: 'LGA1700', cores: 4, threads: 8, base_clock: '3.3GHz', boost_clock: '4.3GHz', tdp: 58 },
    compatibilityKey: 'LGA1700',
  },

  // Motherboards
  {
    id: 'mobo1',
    tipo: ComponentCategory.MOTHERBOARD,
    nome: 'MSI B550 TOMAHAWK',
    brand: 'MSI',
    preco: 900,
    imageUrl: 'https://picsum.photos/seed/mobo1/200/200',
    especificacao: { socket: 'AM4', chipset: 'B550', ram_type: 'DDR4', form_factor: 'ATX' },
    compatibilityKey: 'AM4_DDR4',
  },
  {
    id: 'mobo2',
    tipo: ComponentCategory.MOTHERBOARD,
    nome: 'ASUS ROG STRIX B660-F GAMING WIFI',
    brand: 'ASUS',
    preco: 1300,
    imageUrl: 'https://picsum.photos/seed/mobo2/200/200',
    especificacao: { socket: 'LGA1700', chipset: 'B660', ram_type: 'DDR5', form_factor: 'ATX' },
    compatibilityKey: 'LGA1700_DDR5',
  },
  {
    id: 'mobo3',
    tipo: ComponentCategory.MOTHERBOARD,
    nome: 'Gigabyte X670 AORUS ELITE AX',
    brand: 'Gigabyte',
    preco: 1800,
    imageUrl: 'https://picsum.photos/seed/mobo3/200/200',
    especificacao: { socket: 'AM5', chipset: 'X670', ram_type: 'DDR5', form_factor: 'ATX' },
    compatibilityKey: 'AM5_DDR5',
  },
  {
    id: 'mobo4',
    tipo: ComponentCategory.MOTHERBOARD,
    nome: 'ASUS TUF GAMING Z790-PLUS WIFI',
    brand: 'ASUS',
    preco: 2000,
    imageUrl: 'https://picsum.photos/seed/mobo4/200/200',
    especificacao: { socket: 'LGA1700', chipset: 'Z790', ram_type: 'DDR5', form_factor: 'ATX' },
    compatibilityKey: 'LGA1700_DDR5',
  },
  {
    id: 'mobo5',
    tipo: ComponentCategory.MOTHERBOARD,
    nome: 'MSI MAG B650 TOMAHAWK WIFI',
    brand: 'MSI',
    preco: 1500,
    imageUrl: 'https://picsum.photos/seed/mobo5/200/200',
    especificacao: { socket: 'AM5', chipset: 'B650', ram_type: 'DDR5', form_factor: 'ATX' },
    compatibilityKey: 'AM5_DDR5',
  },
  {
    id: 'mobo6',
    tipo: ComponentCategory.MOTHERBOARD,
    nome: 'Gigabyte H610M S2H DDR4',
    brand: 'Gigabyte',
    preco: 550,
    imageUrl: 'https://picsum.photos/seed/mobo6/200/200',
    especificacao: { socket: 'LGA1700', chipset: 'H610', ram_type: 'DDR4', form_factor: 'Micro-ATX' },
    compatibilityKey: 'LGA1700_DDR4',
  },


  // RAM
  {
    id: 'ram1',
    tipo: ComponentCategory.RAM,
    nome: 'Corsair Vengeance LPX 16GB (2x8GB) DDR4 3200MHz',
    brand: 'Corsair',
    preco: 400,
    imageUrl: 'https://picsum.photos/seed/ram1/200/200',
    especificacao: { type: 'DDR4', capacity_gb: 16, speed_mhz: 3200, modules: 2 },
    compatibilityKey: 'DDR4',
  },
  {
    id: 'ram2',
    tipo: ComponentCategory.RAM,
    nome: 'Kingston Fury Beast 32GB (2x16GB) DDR5 5200MHz',
    brand: 'Kingston',
    preco: 800,
    imageUrl: 'https://picsum.photos/seed/ram2/200/200',
    especificacao: { type: 'DDR5', capacity_gb: 32, speed_mhz: 5200, modules: 2 },
    compatibilityKey: 'DDR5',
  },
  {
    id: 'ram3',
    tipo: ComponentCategory.RAM,
    nome: 'G.Skill Ripjaws V 16GB (2x8GB) DDR4 3600MHz',
    brand: 'G.Skill',
    preco: 450,
    imageUrl: 'https://picsum.photos/seed/ram3/200/200',
    especificacao: { type: 'DDR4', capacity_gb: 16, speed_mhz: 3600, modules: 2 },
    compatibilityKey: 'DDR4',
  },
  {
    id: 'ram4',
    tipo: ComponentCategory.RAM,
    nome: 'Corsair Dominator Platinum RGB 32GB (2x16GB) DDR5 6000MHz',
    brand: 'Corsair',
    preco: 1200,
    imageUrl: 'https://picsum.photos/seed/ram4/200/200',
    especificacao: { type: 'DDR5', capacity_gb: 32, speed_mhz: 6000, modules: 2 },
    compatibilityKey: 'DDR5',
  },
  {
    id: 'ram5',
    tipo: ComponentCategory.RAM,
    nome: 'Crucial Ballistix 8GB (1x8GB) DDR4 3200MHz',
    brand: 'Crucial',
    preco: 200,
    imageUrl: 'https://picsum.photos/seed/ram5/200/200',
    especificacao: { type: 'DDR4', capacity_gb: 8, speed_mhz: 3200, modules: 1 },
    compatibilityKey: 'DDR4',
  },

  // GPUs
  {
    id: 'gpu1',
    tipo: ComponentCategory.GPU,
    nome: 'NVIDIA GeForce RTX 3060 12GB',
    brand: 'NVIDIA',
    preco: 2000,
    imageUrl: 'https://picsum.photos/seed/gpu1/200/200',
    especificacao: { memory_gb: 12, recommended_psu_w: 550 },
  },
  {
    id: 'gpu2',
    tipo: ComponentCategory.GPU,
    nome: 'AMD Radeon RX 6700 XT 12GB',
    brand: 'AMD',
    preco: 2500,
    imageUrl: 'https://picsum.photos/seed/gpu2/200/200',
    especificacao: { memory_gb: 12, recommended_psu_w: 650 },
  },
  {
    id: 'gpu3',
    tipo: ComponentCategory.GPU,
    nome: 'NVIDIA GeForce RTX 4070 12GB',
    brand: 'NVIDIA',
    preco: 4000,
    imageUrl: 'https://picsum.photos/seed/gpu3n/200/200',
    especificacao: { memory_gb: 12, recommended_psu_w: 650 },
  },
  {
    id: 'gpu4',
    tipo: ComponentCategory.GPU,
    nome: 'AMD Radeon RX 7800 XT 16GB',
    brand: 'AMD',
    preco: 3800,
    imageUrl: 'https://picsum.photos/seed/gpu4a/200/200',
    especificacao: { memory_gb: 16, recommended_psu_w: 700 },
  },
  {
    id: 'gpu5',
    tipo: ComponentCategory.GPU,
    nome: 'NVIDIA GeForce GTX 1650 4GB',
    brand: 'NVIDIA',
    preco: 900,
    imageUrl: 'https://picsum.photos/seed/gpu5n/200/200',
    especificacao: { memory_gb: 4, recommended_psu_w: 300 },
  },

  // Storage
  {
    id: 'storage1',
    tipo: ComponentCategory.STORAGE,
    nome: 'Kingston NV2 1TB NVMe PCIe 4.0 SSD',
    brand: 'Kingston',
    preco: 450,
    imageUrl: 'https://picsum.photos/seed/storage1/200/200',
    especificacao: { type: 'NVMe SSD', capacity_tb: 1, interface: 'PCIe 4.0' },
  },
  {
    id: 'storage2',
    tipo: ComponentCategory.STORAGE,
    nome: 'Samsung 970 EVO Plus 2TB NVMe PCIe 3.0 SSD',
    brand: 'Samsung',
    preco: 900,
    imageUrl: 'https://picsum.photos/seed/storage2/200/200',
    especificacao: { type: 'NVMe SSD', capacity_tb: 2, interface: 'PCIe 3.0' },
  },
  {
    id: 'storage3',
    tipo: ComponentCategory.STORAGE,
    nome: 'Western Digital Black SN850X 2TB NVMe PCIe 4.0 SSD',
    brand: 'Western Digital',
    preco: 1200,
    imageUrl: 'https://picsum.photos/seed/storage3/200/200',
    especificacao: { type: 'NVMe SSD', capacity_tb: 2, interface: 'PCIe 4.0', speed_mbps: 7300 },
  },
  {
    id: 'storage4',
    tipo: ComponentCategory.STORAGE,
    nome: 'Crucial MX500 500GB SATA SSD',
    brand: 'Crucial',
    preco: 250,
    imageUrl: 'https://picsum.photos/seed/storage4/200/200',
    especificacao: { type: 'SATA SSD', capacity_gb: 500, interface: 'SATA III' },
  },
  {
    id: 'storage5',
    tipo: ComponentCategory.STORAGE,
    nome: 'Seagate Barracuda 4TB HDD',
    brand: 'Seagate',
    preco: 400,
    imageUrl: 'https://picsum.photos/seed/storage5/200/200',
    especificacao: { type: 'HDD', capacity_tb: 4, interface: 'SATA III', rpm: 5400 },
  },


  // PSUs
  {
    id: 'psu1',
    tipo: ComponentCategory.PSU,
    nome: 'Corsair RM750x 750W 80+ Gold',
    brand: 'Corsair',
    preco: 700,
    imageUrl: 'https://picsum.photos/seed/psu1/200/200',
    especificacao: { wattage_w: 750, efficiency: '80+ Gold', modular: 'Full' },
  },
  {
    id: 'psu2',
    tipo: ComponentCategory.PSU,
    nome: 'Cooler Master MWE 650 Bronze V2',
    brand: 'Cooler Master',
    preco: 400,
    imageUrl: 'https://picsum.photos/seed/psu2/200/200',
    especificacao: { wattage_w: 650, efficiency: '80+ Bronze', modular: 'Non-Modular' },
  },
  {
    id: 'psu3',
    tipo: ComponentCategory.PSU,
    nome: 'Seasonic FOCUS GX-850 850W 80+ Gold',
    brand: 'Seasonic',
    preco: 850,
    imageUrl: 'https://picsum.photos/seed/psu3s/200/200',
    especificacao: { wattage_w: 850, efficiency: '80+ Gold', modular: 'Full' },
  },
  {
    id: 'psu4',
    tipo: ComponentCategory.PSU,
    nome: 'EVGA 550 B5 550W 80+ Bronze',
    brand: 'EVGA',
    preco: 350,
    imageUrl: 'https://picsum.photos/seed/psu4e/200/200',
    especificacao: { wattage_w: 550, efficiency: '80+ Bronze', modular: 'Full' }, // Changed to Full for variety
  },
   {
    id: 'psu5',
    tipo: ComponentCategory.PSU,
    nome: 'Corsair HX1000i 1000W 80+ Platinum',
    brand: 'Corsair',
    preco: 1500,
    imageUrl: 'https://picsum.photos/seed/psu5c/200/200',
    especificacao: { wattage_w: 1000, efficiency: '80+ Platinum', modular: 'Full' },
  },

  // Cases
  {
    id: 'case1',
    tipo: ComponentCategory.CASE,
    nome: 'NZXT H510 Flow',
    brand: 'NZXT',
    preco: 500,
    imageUrl: 'https://picsum.photos/seed/case1/200/200',
    especificacao: { type: 'Mid Tower', color: 'Black', mobo_support: ['ATX', 'Micro-ATX', 'Mini-ITX'], dust_filters: 'Yes' },
  },
  {
    id: 'case2',
    tipo: ComponentCategory.CASE,
    nome: 'Lian Li Lancool II Mesh',
    brand: 'Lian Li',
    preco: 650,
    imageUrl: 'https://picsum.photos/seed/case2/200/200',
    especificacao: { type: 'Mid Tower', color: 'White', mobo_support: ['ATX', 'Micro-ATX', 'Mini-ITX'], dust_filters: 'Yes', airflow: 'High' },
  },
  {
    id: 'case3',
    tipo: ComponentCategory.CASE,
    nome: 'Fractal Design Meshify 2 Compact',
    brand: 'Fractal Design',
    preco: 700,
    imageUrl: 'https://picsum.photos/seed/case3f/200/200',
    especificacao: { type: 'Mid Tower', color: 'Black', mobo_support: ['ATX', 'Micro-ATX', 'Mini-ITX'], dust_filters: 'Full', airflow: 'High' },
  },
  {
    id: 'case4',
    tipo: ComponentCategory.CASE,
    nome: 'Cooler Master MasterBox Q300L',
    brand: 'Cooler Master',
    preco: 300,
    imageUrl: 'https://picsum.photos/seed/case4cm/200/200',
    especificacao: { type: 'Micro-ATX Tower', color: 'Black', mobo_support: ['Micro-ATX', 'Mini-ITX'], dust_filters: 'Top, Bottom' },
  },
  {
    id: 'case5',
    tipo: ComponentCategory.CASE,
    nome: 'Corsair 7000D Airflow',
    brand: 'Corsair',
    preco: 1200,
    imageUrl: 'https://picsum.photos/seed/case5c/200/200',
    especificacao: { type: 'Full Tower', color: 'Black', mobo_support: ['E-ATX', 'ATX', 'Micro-ATX', 'Mini-ITX'], dust_filters: 'Full', airflow: 'Extreme' },
  },


  // Coolers
  {
    id: 'cooler1',
    tipo: ComponentCategory.COOLER,
    nome: 'Cooler Master Hyper 212 Black Edition',
    brand: 'Cooler Master',
    preco: 250,
    imageUrl: 'https://picsum.photos/seed/cooler1/200/200',
    especificacao: { type: 'Air Cooler', tdp_rating_w: 150, socket_support: ['AM4', 'AM5', 'LGA1700', 'LGA1200'] },
  },
  {
    id: 'cooler2',
    tipo: ComponentCategory.COOLER,
    nome: 'Noctua NH-D15',
    brand: 'Noctua',
    preco: 600,
    imageUrl: 'https://picsum.photos/seed/cooler2/200/200',
    especificacao: { type: 'Air Cooler', tdp_rating_w: 220, socket_support: ['AM4', 'AM5', 'LGA1700', 'LGA1200'], noise_level: 'Low' },
  },
  {
    id: 'cooler3',
    tipo: ComponentCategory.COOLER,
    nome: 'Arctic Liquid Freezer II 240',
    brand: 'Arctic',
    preco: 700,
    imageUrl: 'https://picsum.photos/seed/cooler3a/200/200',
    especificacao: { type: 'AIO Liquid Cooler', radiator_size_mm: 240, tdp_rating_w: 250, socket_support: ['AM4', 'AM5', 'LGA1700', 'LGA1200'] },
  },
  {
    id: 'cooler4',
    tipo: ComponentCategory.COOLER,
    nome: 'Noctua NH-L9i',
    brand: 'Noctua',
    preco: 300,
    imageUrl: 'https://picsum.photos/seed/cooler4n/200/200',
    especificacao: { type: 'Low Profile Air Cooler', tdp_rating_w: 95, socket_support: ['LGA1700', 'LGA1200', 'LGA115x'], noise_level: 'Very Low' },
  },
  {
    id: 'cooler5',
    tipo: ComponentCategory.COOLER,
    nome: 'Deepcool AK620',
    brand: 'Deepcool',
    preco: 450,
    imageUrl: 'https://picsum.photos/seed/cooler5d/200/200',
    especificacao: { type: 'Air Cooler', tdp_rating_w: 260, socket_support: ['AM4', 'AM5', 'LGA1700', 'LGA1200', 'LGA2066'], noise_level: 'Moderate' },
  },
];
